import {
  type CslTemplate,
  renderBibliography,
  templateForStyle,
} from "../csl/render";
import type { PaperDocument, ReferenceEntry } from "../doc/types";

/**
 * Rebuild the paper as LaTeX: structure via \section levels, in-text markers
 * converted to \cite{...} keys, and the bibliography rendered through
 * citeproc (CSL) in a style matching the paper's detected citation style —
 * never hand-formatted. The round trip preserves every reference entry.
 */
export function exportLatex(
  doc: PaperDocument,
  styleOverride?: CslTemplate,
): string {
  const lines: string[] = [
    "% Generated by Paper Improvement Agent",
    "% Citations preserved from the parsed document; bibliography rendered via CSL (citeproc).",
    "\\documentclass{article}",
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage{hyperref}",
    "",
    `\\title{${escapeLatex(doc.title)}}`,
    "\\date{}",
    "",
    "\\begin{document}",
    "\\maketitle",
    "",
  ];

  if (doc.abstract) {
    lines.push(
      "\\begin{abstract}",
      escapeLatex(doc.abstract),
      "\\end{abstract}",
      "",
    );
  }

  for (const section of doc.sections) {
    if (section.level === 0) continue; // front matter noise
    const command =
      section.level >= 3
        ? "subsubsection"
        : section.level === 2
          ? "subsection"
          : "section";
    // Strip leading list numbering — LaTeX numbers sections itself.
    const heading = section.heading.replace(/^\d+(\.\d+)*\.?\s+/, "");
    lines.push(`\\${command}{${escapeLatex(heading)}}`, "");
    for (const paragraph of section.paragraphs) {
      lines.push(convertMarkers(escapeLatex(paragraph), doc), "");
    }
  }

  lines.push(
    renderThebibliography(doc, styleOverride),
    "",
    "\\end{document}",
    "",
  );
  return lines.join("\n");
}

/** Minimal BibTeX companion so the references also survive as data. */
export function exportBibtex(doc: PaperDocument): string {
  return doc.citations.entries.map(bibtexEntry).join("\n\n");
}

export function escapeLatex(text: string): string {
  return text
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/⟦\^([\d\s,;–-]+)⟧/g, "[$1]"); // sup tokens back to plain markers
}

/**
 * Replace in-text markers with \cite keys. Numeric brackets ("[1]", "[2, 5]",
 * "[1-3]") map through the entry markers; author-year parentheticals map by
 * the same surname+year matching P6 uses (via the stored marker graph).
 */
export function convertMarkers(text: string, doc: PaperDocument): string {
  const byMarker = new Map(
    doc.citations.entries
      .filter((e) => e.marker)
      .map((e) => [e.marker as string, e.id]),
  );

  return text.replace(
    /\[(\d{1,3}(?:\s*[,–-]\s*\d{1,3})*)\]/g,
    (whole, list: string) => {
      const keys: string[] = [];
      for (const part of list.split(/[,;]/)) {
        const range = part.split(/[–-]/).map((s) => Number(s.trim()));
        if (
          range.length === 2 &&
          Number.isFinite(range[0]) &&
          Number.isFinite(range[1])
        ) {
          for (let n = range[0]; n <= range[1]; n++) {
            const id = byMarker.get(String(n));
            if (id) keys.push(id);
          }
        } else if (Number.isFinite(range[0])) {
          const id = byMarker.get(String(range[0]));
          if (id) keys.push(id);
        }
      }
      return keys.length > 0 ? `\\cite{${keys.join(",")}}` : whole;
    },
  );
}

function renderThebibliography(
  doc: PaperDocument,
  styleOverride?: CslTemplate,
): string {
  const entries = doc.citations.entries;
  if (entries.length === 0) return "";

  const template =
    styleOverride ?? templateForStyle(doc.citations.citationStyle);
  const lines = [`\\begin{thebibliography}{${entries.length}}`];
  for (const entry of entries) {
    lines.push(
      `\\bibitem{${entry.id}} ${escapeLatex(formatEntry(entry, template))}`,
    );
  }
  lines.push("\\end{thebibliography}");
  return lines.join("\n");
}

/** One entry through citeproc; raw text as honest fallback for unparsed CSL. */
export function formatEntry(
  entry: ReferenceEntry,
  template: ReturnType<typeof templateForStyle>,
): string {
  try {
    const rendered = renderBibliography([entry.csl], template)
      .trim()
      .replace(/\s+/g, " ");
    // citeproc emits a leading list index for numeric styles; strip it — LaTeX numbers items.
    return rendered.replace(/^\d+\.\s*/, "") || entry.rawText;
  } catch {
    return entry.rawText;
  }
}

function bibtexEntry(entry: ReferenceEntry): string {
  const c = entry.csl;
  const kind =
    c.type === "paper-conference"
      ? "inproceedings"
      : c.type === "book"
        ? "book"
        : "article";
  const fields: [string, string | undefined][] = [
    ["title", c.title],
    [
      "author",
      c.author
        ?.map(
          (a) => a.literal ?? [a.family, a.given].filter(Boolean).join(", "),
        )
        .join(" and "),
    ],
    ["year", c.issued?.["date-parts"]?.[0]?.[0]?.toString()],
    [kind === "inproceedings" ? "booktitle" : "journal", c["container-title"]],
    ["volume", c.volume],
    ["pages", c.page],
    ["doi", c.DOI],
    ["url", c.URL],
  ];
  const body = fields
    .filter((f): f is [string, string] => Boolean(f[1]))
    .map(([k, v]) => `  ${k} = {${v.replace(/[{}]/g, "")}}`)
    .join(",\n");
  return `@${kind}{${entry.id},\n${body}\n}`;
}
